name: ${project.name}
main: com.poixson.computerparts.ComputerPartsPlugin
version: ${project.version}
api-version: ${spigot-short-version}
load: STARTUP
depend: [ pxnCommonBukkit ]
authors: [ lorenzop ]
website: ${project.url}
description: ${project.description}
commands:
    computer:
        description: "Commands to manage computer parts"
        usage: "Usage: /computer <cmd>"
    computerparts:
        description: "Commands to manage computer parts"
        usage: "Usage: /computerparts <cmd>"
    parts:
        description: "Commands to manage computer parts"
        usage: "Usage: /parts <cmd>"
permission-message: "You don't have permission to use this command."
permissions:
    computer.*:
        default: op
        description: Gives access to all computer commands
        children:
            computer.blink: true
    computer.blink:
        default: op
        description: Blink the IO Ports near the player
